version: 1.0.{build}

branches:
  only:
    - master

skip_commits:
  files:
    - docs/*

image: Visual Studio 2017

environment:
  nodejs_version: "9"

platform:
  - x64

configuration:
  - Release
  - Debug

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - node --version
  - npm --version

before_build:
    - tree . /f /a
    - mkdir build && cd build && cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH="C:\\Qt\\5.10.0\\msvc2017_64" -DBOOST_ROOT="C:\\Libraries\\boost_1_65_1" ..

build:
  parallel: true
  verbosity: normal
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

deploy:
- provider: BinTray
  username: l0l022
  api_key:
    secure: $env:bintray_key
  subject: l0l022
  repo: Windows
  package: ProjetTuteure
  publish: true
  override: true
