version: 1.0.{build}

branches:
  only:
    - master

skip_commits:
  files:
    - docs/*

image: Visual Studio 2017

environment:
  nodejs_version: "9"

platform:
  - x64

configuration:
  - Release
#  - Debug

install:
  - ps: Install-Product node $env:nodejs_version
  - set VCINSTALLDIR="C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\"
  - set PATH=C:\Qt\5.10.0\msvc2017_64\bin;%PATH%

cache:
  - src\presentation\ui\node_modules

test_script:
  - node --version
  - npm --version

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH="C:\\Qt\\5.10.0\\msvc2017_64" -DBOOST_ROOT="C:\\Libraries\\boost_1_65_1" ..
    - cd ..

build:
  parallel: true
  verbosity: minimal
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

after_build:
  - cd build
  - mkdir ProjetTuteure && cd ProjetTuteure
  - cp ..\\src\\%CONFIGURATION%\\app.exe .
  - windeployqt app.exe
  - cd ..\\..

artifacts:
  - path: build\ProjetTuteure
    name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_BUILD_VERSION)-$(PLATFORM)-$(CONFIGURATION)

deploy:
- provider: BinTray
  username: l0l022
  api_key:
    secure: u0wfFz6Hkdwsfopz+Zpyp5wCY7TFCkDDnwY6DiWMBWz7WCDG+M+NXn7M/HW/IRmp
  subject: l0l022
  repo: Windows
  package: ProjetTuteure
  publish: true
  override: true
