PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS T_FORM_FRM(
FRM_ID INTEGER PRIMARY KEY NOT NULL,
FRM_NAME TEXT NOT NULL,
FRM_DESCRIPTION TEXT NOT NULL,
FRM_CREATION_DATE INTEGER NOT NULL,
FRM_MODIFICATION_DATE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS T_QUESTION_QST(
QST_ID INTEGER PRIMARY KEY NOT NULL,
FRM_ID INTEGER NOT NULL,
QST_TYPE TEXT NOT NULL,
QST_TITLE TEXT NOT NULL,
QST_NBWORDS INTEGER NOT NULL,
QST_MODIFICATION_DATE INTEGER NOT NULL,
FOREIGN KEY (FRM_ID) REFERENCES T_FORM_FRM(FRM_ID)
);

CREATE TABLE IF NOT EXISTS T_CHOICE_CHC(
CHC_ID INTEGER PRIMARY KEY NOT NULL,
QST_ID INTEGER NOT NULL,
CHC_MODIFICATION_DATE INTEGER NOT NULL,
CHC_LABEL TEXT NOT NULL,
FOREIGN KEY (QST_ID) REFERENCES T_QUESTION_QST(QST_ID)
);

CREATE TABLE IF NOT EXISTS T_SUBJECT_SBJ(
SBJ_ID INTEGER PRIMARY KEY NOT NULL,
FRM_ID INTEGER NOT NULL,
SBJ_MODIFICATION_DATE INTEGER NOT NULL,
SBJ_ISVALID INTEGER NOT NULL,
FOREIGN KEY (FRM_ID) REFERENCES T_FORM_FRM(FRM_ID)
);

CREATE TABLE IF NOT EXISTS TJ_SBJ_QST(
SBJ_ID INTEGER NOT NULL,
QST_ID INTEGER NOT NULL,
SBJ_QST_MODIFICATION_DATE INTEGER NOT NULL,
SBJ_QST_WORDS TEXT NOT NULL,
FOREIGN KEY (SBJ_ID) REFERENCES T_SUBJECT_SBJ(SBJ_ID),
FOREIGN KEY (QST_ID) REFERENCES T_QUESTION_QST(QST_ID)
);

CREATE TABLE IF NOT EXISTS TJ_SBJ_CHC(
SBJ_ID INTEGER NOT NULL,
CHC_ID INTEGER NOT NULL,
SBJ_CHC_MODIFICATION_DATE INTEGER NOT NULL,
FOREIGN KEY (SBJ_ID) REFERENCES T_SUBJECT_SBJ(SBJ_ID),
FOREIGN KEY (CHC_ID) REFERENCES T_CHOICE_CHC(CHC_ID)
);

/* no */

CREATE TABLE IF NOT EXISTS SUBSITUENT_TERM(
ID_SUBSTITUENT_TERM INTEGER PRIMARY KEY,
MODIFICATION_DATE DATE NOT NULL,
WORD TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SUBSTITUTED_TERM(
ID_SUBSTITUENT_TERM INTEGER,
WORD TEXT NOT NULL,
PRIMARY KEY (ID_SUBSTITUENT_TERM, WORD),
FOREIGN KEY (ID_SUBSTITUENT_TERM) REFERENCES SUBSITUENT_TERM(ID_SUBSTITUENT_TERM)
);
